---
- name: Configures all rpis
  hosts: kitchen_pi,tv_pi
  tasks:
    - name: Update all packages to their latest version # noqa: package-latest
      ansible.builtin.apt:
        update_cache: true
        name: "*"
        state: latest
